### ISSUE TITLE
Can't find the pluggin in the Option 

### ISSUE THREAD

**Issue by everchump** [falconmick/BattleCryPluggin#1]
I  extract the zip  into the pluggin folder；

so the directory is ：  plugin>>BattleCry>>"AudioFiles" folder  and the "battlecry.dll“ 

but Can't find the pluggin in the HDT Option (0.13.9 HDT)

if the directory is ：  plugin>>"AudioFiles" folder  and the "battlecry.dll“ 

then i can find the pluggin in the HDT Option.

so，is it my problem ?

**Comment by falconmick** [comment]
I think your problem might be that you have the plugin inside of a folder called "BattleCry", This extra folder is not required and will probably break it. the folder hirachi should look like this:

Hearthstone Deck Tracker/
------Plugin/
------------battlecry.dll
------------AudioFiles/
------------------johncena.mp3
------------------cardsoundconfig.xml

If that fixes it please let me know and I'll update the readme to make this more clear.

Cheers.

**Comment by everchump** [comment]
Yes , without the "battlecry" folder  it works， I know it.

I just want it works with the "battlecry" folder too. 

because the others pluggins，such as your Anyfin Can Lethal，HearthstoneCollectionTracker，RenoTime ....etc ， they all have a folder inside the Plugin.

Hearthstone Deck Tracker/
------Plugin/
------------BattleCry/
-----------------battlecry.dll
------------------AudioFiles/
--------------------------johncena.mp3
--------------------------cardsoundconfig.xml

i want this works.....

**Comment by falconmick** [comment]
You would have to put a request into [Hearthstone Deck Tracker](https://github.com/Epix37/Hearthstone-Deck-Tracker) for functionality like that. I don't have any options other than to put my dll into the root of the plugin folder.

**Comment by azeier** [comment]
HDT supports loading plugins from sub-folders. The problem is that you are looking for the `cardsoundconfig.xml` in `Plugins/AudioFiles` ([here](https://github.com/falconmick/BattleCryPluggin/blob/master/BattleCry/BattleCryPlugin.cs#L17)).

Exception from the log when trying to load plugin from a sub-folder:

```
[22:50:27] PluginManager: Error Loading [...]\Plugins\BattleCry\BattleCry.dll:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. 
---> System.IO.DirectoryNotFoundException: Could not find a part of the path '[...]\Plugins\AudioFiles\cardsoundconfig.xml'.
```

**Comment by falconmick** [comment]
Ah wikid, I had no idea you could do that. @Epix37 is there a way to get the location of the dll via your api or will I have to use some reflection to get the source of the dll?

**Comment by azeier** [comment]
Not possible at the moment, reflection should be the easiest solution.

**Comment by falconmick** [comment]
@Epix37 
![image](https://cloud.githubusercontent.com/assets/713449/12711325/edf9c8c6-c923-11e5-9d59-df3c10953402.png)
this is the folder setup
![image](https://cloud.githubusercontent.com/assets/713449/12711338/fcef9dc4-c923-11e5-974a-98a081c6f408.png)
It's not showing up. Any suggestions?

**Comment by azeier** [comment]
Check the log: `options > tracker > settings > show log` or `%AppData%/HearthstoneDeckTracker/Logs`.

**Comment by falconmick** [comment]
@everchump https://github.com/falconmick/BattleCryPluggin/releases/tag/0.0.4b

**Comment by seregapsa** [comment]
Не работает плагин. Распаковывал файлы как здесь написано. но звук все равно не воспроизводится.

**Comment by falconmick** [comment]
@seregapsa could you please show me your folder setup? 

не могли бы вы показать мне ваши настройки папки ?

**Comment by seregapsa** [comment]
Извините не совсем  понял какие настройки и какой папки показать??   А будет ли этот мод работать если у меня русский клиент?

Sorry do not quite understand what settings and what folder to show?? And will this mod work if I have a Russian client?
