### ISSUE TITLE
Can I add a few cards?

### ISSUE THREAD

**Issue by pashadizel** [falconmick/BattleCryPluggin#3]
I don't understand, how file should look like, if I add 2 cards (eg. Mysterious Challenger and Alexstrasza). Can you show me a code for two cards?

**Comment by falconmick** [comment]
Hey man, sorry it's midnight here so tomorrow morning I'll jump on and make an example for you.

**Comment by falconmick** [comment]
## ![image](https://cloud.githubusercontent.com/assets/713449/14230149/643078ee-f9a0-11e5-989a-680583602b8c.png)

## ![image](https://cloud.githubusercontent.com/assets/713449/14230153/7b4a5392-f9a0-11e5-996e-426969098826.png)

## ![image](https://cloud.githubusercontent.com/assets/713449/14230154/89bce124-f9a0-11e5-9594-c5118242a835.png)

## ![image](https://cloud.githubusercontent.com/assets/713449/14230165/c67f61b8-f9a0-11e5-8a65-de87598d6ff0.png)

## ![image](https://cloud.githubusercontent.com/assets/713449/14230175/ecbc8720-f9a0-11e5-90c1-f6fba607869e.png)

## ![image](https://cloud.githubusercontent.com/assets/713449/14230140/2c93733c-f9a0-11e5-96bd-c82370568842.png)

**Comment by pashadizel** [comment]
Thank you so much!
