### ISSUE TITLE
Cannot assign new sounds

### ISSUE THREAD

**Issue by RobotGandhi** [falconmick/BattleCryPluggin#4]
I don't know if I'm just doing something wrong, but after adding some extra code for Rafaam, he won't play his assigned sound in game. I was playing against the Innkeeper, and had Deck Tracker activated.
![code](https://cloud.githubusercontent.com/assets/15279015/15009974/f722bdd6-11e9-11e6-9bc7-e4e6998a0c2b.png)
(The extra code)
![path to files](https://cloud.githubusercontent.com/assets/15279015/15009975/f7239a30-11e9-11e6-85fc-150bb7e3d5a4.png)
(The files in the Plugin folder)

**Comment by falconmick** [comment]
It might have been to do with a version mismatch of the HDT API as mentioned here:
https://github.com/falconmick/BattleCryPluggin/issues/5

Could you please re-try?
